#!/usr/bin/env python3
"""Write docs/oss.md: where each installed skill comes from, its license, and how to install it.

Sources come from the skills CLI lock files. Licenses come from the GitHub API through `gh`.
"""
import collections
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import router  # noqa: E402
import skills  # noqa: E402

HOME = Path.home()
LOCKS = [HOME / ".agents" / ".skill-lock.json", HOME / "Development" / "skills-lock.json"]
KNOWN = {"gsd-": "gsd-build/get-shit-done", "potpie-": "potpie-ai/potpie"}
INSTALL = {"gsd-build/get-shit-done": "npm package `get-shit-done-cc`",
           "potpie-ai/potpie": "installed with the `potpie` CLI"}


def sources():
    out = {}
    for f in LOCKS:
        if f.exists():
            sk = json.loads(f.read_text()).get("skills", {})
            for name, v in (sk.items() if isinstance(sk, dict) else []):
                if isinstance(v, dict) and v.get("source"):
                    out[name] = v["source"]
    return out


def license_of(repo):
    r = subprocess.run(["gh", "api", f"repos/{repo}", "--jq", '.license.spdx_id // "none"'],
                       capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else "unknown"


def main():
    src = sources()
    by_repo = collections.defaultdict(list)
    for s in skills.load_catalog(router.STATE_DIR)["skills"]:
        repo = src.get(s["name"]) or next((r for p, r in KNOWN.items() if s["name"].startswith(p)), None)
        by_repo[(repo or "").lower() or None].append(s["name"])
    rows, unknown = [], by_repo.pop(None, [])
    for repo, names in sorted(by_repo.items(), key=lambda x: -len(x[1])):
        lic = license_of(repo)
        oss = "Yes" if lic not in ("none", "unknown", "NOASSERTION") else "Check" if lic == "NOASSERTION" else "No"
        how = INSTALL.get(repo, f"`npx skills add {repo} -g -a '*'`")
        rows.append(f"| [{repo}](https://github.com/{repo}) | {lic} | {oss} | {len(names)} | "
                    f"{', '.join(sorted(names)[:6])}{' and more' if len(names) > 6 else ''} | {how} |")
    total = sum(len(v) for v in by_repo.values()) + len(unknown)
    doc = f"""# Open-source skills and tools

What the author's setup uses, where each piece comes from, and whether you can install it
yourself. Generated by `python3 scripts/inventory.py` from the skills CLI lock files and the
GitHub API. {total} skills, {total - len(unknown)} with a known source.

## Skills by source

"Yes" means the repo has an open-source license. "Check" means GitHub could not identify the
license, so read it before redistributing. "No" means no license, so all rights are reserved.

| Source | License | Open source | Skills | Includes | Install |
| --- | --- | --- | --- | --- | --- |
{chr(10).join(rows)}

`-a '*'` installs a skill for every agent the skills CLI supports, including Codex and OpenCode,
not only Claude Code. Add `-s <name>` to take one skill from a repo.

## Skills with no recorded source

{", ".join(sorted(unknown)) if unknown else "None."}

These were installed by hand or by another tool. They may be your own or copied from elsewhere,
so they are not listed as open source.

## Tools

| Tool | What it does here | License | Source |
| --- | --- | --- | --- |
| jev-router | This repo | No license file yet | [0xSarnavo/jev-router](https://github.com/0xSarnavo/jev-router) |
| Jev | Hosted routing model | Proprietary service, needs an API key | [docs.typesafe.ai](https://docs.typesafe.ai) |
| Laya | Local routing model with Jev's API | Apache-2.0 | [convaiinnovations/laya](https://huggingface.co/convaiinnovations/laya) |
| Potpie | Project memory: decisions, features, bugs | Apache-2.0 | [potpie-ai/potpie](https://github.com/potpie-ai/potpie) |
| graphify | Code graph: callers, callees, impact | Apache-2.0 | [Graphify-Labs/graphify](https://github.com/Graphify-Labs/graphify), PyPI `graphifyy` |
| GSD | Planning, progress and handoff files | MIT | [gsd-build/get-shit-done](https://github.com/gsd-build/get-shit-done), npm `get-shit-done-cc` |

MCP servers such as Railway, TinyFish and Figma are hosted services or vendor CLIs with their own
terms, so they are not listed as open source here.
"""
    (ROOT / "docs" / "oss.md").write_text(doc)
    print(f"wrote docs/oss.md: {total} skills, {len(rows)} sources, {len(unknown)} unknown")


if __name__ == "__main__":
    main()
